version: "3.9"

services:
  db_main:
    image: postgres:15
    environment:
      POSTGRES_DB: "${DB_MAIN_DATABASE}"
      POSTGRES_USER: "${DB_MAIN_USER}"
      POSTGRES_PASSWORD: "${DB_MAIN_PASSWORD}"
    volumes:
      - db_main_storage:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data

  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_storage:/data
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_PORT: 6379

volumes:
  db_main_storage:
    driver: local
  minio_storage:
    driver: local
  redis_storage:
    driver: local